In [1]:
#homework 1 question 6 
# Forward Elimination to solve a nonsingular lower-triangular system
import numpy as np
from scipy.linalg import solve

def forward_sub(al, ab):
    x = np.zeros((ab.shape))
    for i in range(len(ab)):
        x[i] = ab[i]
        for j in range(i):  
            x[i] = x[i]-(al[i, j]*x[j]) 
        x[i] = x[i]/al[i, i]
    
    return x

al = np.tril(np.random.randint(1,10,(5,5))).astype(float)
ab = np.random.randint(1,10,(5,1)).astype(float)
#print("this is y : ", y)
x = forward_sub(al,ab)
print("my answer:\n\n",x,"\n")
print("numpy answer\n\n",np.linalg.solve(al,ab),"\n")
#print("scipy answer:\n\n",solve(l,y),"\n")



[[8. 0. 0. 0. 0.]
 [2. 7. 0. 0. 0.]
 [2. 5. 3. 0. 0.]
 [5. 9. 3. 3. 0.]
 [1. 2. 1. 2. 8.]]
my answer:

 [[ 1.125     ]
 [ 0.53571429]
 [-0.64285714]
 [-0.17261905]
 [ 0.97395833]] 

numpy answer

 [[ 1.125     ]
 [ 0.53571429]
 [-0.64285714]
 [-0.17261905]
 [ 0.97395833]] 

