In [6]:
#ignore this one


'''
import numpy as np


def gram_schmidt_modified(A):
    n = A.shape[1]
    
    for j in range(n):
        r=np.linalg.norm(A[:,j])
        A[:,j]=A[:, j] / r
        for k in range(j+1, n-1):
            
            A[:, j] -= np.dot(A[:, k], A[:, j]) * A[:, k]
        #A[:, j] = A[:, j] / np.linalg.norm(A[:, j])
        
        
    return A


A = np.array([[1.0, 1.0, 0.0], [1.0, 3.0, 1.0], [2.0, -1.0, 1.0]])
print(gram_schmidt_modified(A))
'''

[[-0.40824829  0.30151134  0.        ]
 [-2.04124145  0.90453403  0.70710678]
 [ 1.63299316 -0.30151134  0.70710678]]


In [5]:
#this is the one!!!

import math
import numpy as np
def gramSchmidtRefined(A):
    n=A.shape[0]
    a= np.transpose(A)
    r= np.zeros(A.shape, dtype=A.dtype)   #is all this really necessary?>
    q=np.copy(a)
    for i in range(n):
        r[i,i]= math.sqrt(np.dot(q[:,i],q[:,i]))
        q[:,i]=q[:,i]/r[i,i] # need rii to not be zero... Im going to let itbe for noew
        for j in range(i+1,n):
            r[i,j]=np.dot(q[:,i],q[:,j])
            q[:,j]=q[:,j]-((r[i,j])*q[:,i])
            
    return q,r
A= np.array([[1.0,1.0,0.0],[1.0,0.0,1.0],[0.0,1.0,1.0]])
q,r=gramSchmidtRefined(A)

print("This is A: \n", A)
print("This is q : \n", q)
print("This is r : \n", r)
print("This is q times r : \n", np.dot(q,r))


This is A: 
 [[1. 1. 0.]
 [1. 0. 1.]
 [0. 1. 1.]]
This is q : 
 [[ 0.70710678  0.40824829 -0.57735027]
 [ 0.70710678 -0.40824829  0.57735027]
 [ 0.          0.81649658  0.57735027]]
This is r : 
 [[1.41421356 0.70710678 0.70710678]
 [0.         1.22474487 0.40824829]
 [0.         0.         1.15470054]]
This is q times r : 
 [[1.00000000e+00 1.00000000e+00 4.02426802e-17]
 [1.00000000e+00 1.73428748e-19 1.00000000e+00]
 [0.00000000e+00 1.00000000e+00 1.00000000e+00]]
